services:
  apireport:
    image: apireportinterview
    build:
      context: ../App.InterViews.Report
      dockerfile: ../App.InterViews.Report/Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/App.InterViews.Report.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
    ports:
      - "8081:80"
      - "443:443"
    networks:
      - servicenetwork
    command: /bin/sh -c "chmod 644 /root/.aspnet/https/App.InterViews.Report.pfx"

networks:
  servicenetwork:
    external: true