// <auto-generated />
using System;
using App.InterViews.Report.Db.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.InterViews.Report.Migrations.Migrations
{
    [DbContext(typeof(DbDataContext))]
    [Migration("20220816024314_updateVariables")]
    partial class updateVariables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("App.InterViews.Report.Library.Entities.Company", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompany"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCompany");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("App.InterViews.Report.Library.Entities.InterView", b =>
                {
                    b.Property<int>("IdInterview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInterview"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInterView")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProcess")
                        .HasColumnType("int");

                    b.Property<string>("InterViewersName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessIdProcess")
                        .HasColumnType("int");

                    b.Property<string>("TypeInterView")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdInterview");

                    b.HasIndex("ProcessIdProcess");

                    b.ToTable("InterViews");
                });

            modelBuilder.Entity("App.InterViews.Report.Library.Entities.Process", b =>
                {
                    b.Property<int>("IdProcess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcess"), 1L, 1);

                    b.Property<int?>("CompanyIdCompany")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<string>("JobPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RangeSalarial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProcess");

                    b.HasIndex("CompanyIdCompany");

                    b.ToTable("Process");
                });

            modelBuilder.Entity("App.InterViews.Report.Library.Entities.InterView", b =>
                {
                    b.HasOne("App.InterViews.Report.Library.Entities.Process", null)
                        .WithMany("Interviews")
                        .HasForeignKey("ProcessIdProcess");
                });

            modelBuilder.Entity("App.InterViews.Report.Library.Entities.Process", b =>
                {
                    b.HasOne("App.InterViews.Report.Library.Entities.Company", null)
                        .WithMany("Process")
                        .HasForeignKey("CompanyIdCompany");
                });

            modelBuilder.Entity("App.InterViews.Report.Library.Entities.Company", b =>
                {
                    b.Navigation("Process");
                });

            modelBuilder.Entity("App.InterViews.Report.Library.Entities.Process", b =>
                {
                    b.Navigation("Interviews");
                });
#pragma warning restore 612, 618
        }
    }
}
