name: Build and Publish Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install OpenSSL
      run: sudo apt-get install openssl

    - name: Generate private key and CSR
      run: openssl req -newkey rsa:2048 -nodes -keyout key.pem -out csr.pem -subj "/CN=example.com"

    - name: Self-sign certificate
      run: openssl x509 -req -days 365 -in csr.pem -signkey key.pem -out cert.pem

    - name: Convert certificate and private key to PKCS#12 (PFX) format
      run: openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in cert.pem -password pass:12345678
      
    - name: Build Docker image
      run: docker build -t interviewreportapp .

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        preferLatestVersion: true

    - name: Determine Version
      id: version
      uses: gittools/actions/gitversion/execute@v0
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Tag Docker image
      run: docker tag interviewreportapp ${{ secrets.DOCKER_USERNAME }}/interviewreportapp:${{ steps.version.outputs.buildMetaData  }}
    
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/interviewreportapp:${{ steps.version.outputs.buildMetaData  }}

