name: Docker Image CI
on:
  push:
    branches: [ "testDocker" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag appinterviewreport:$(date +%s)
