name: Build and Publish Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build Docker image
      run: docker build -t interviewreportapp .

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0' # Ajusta según tu versión de .NET

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Get version
      id: version
      run: dotnet-gitversion
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Tag Docker image
      run: docker tag interviewreportapp ${{ secrets.DOCKER_USERNAME }}/interviewreportapp:${{ steps.version.outputs.version }}
    
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/interviewreportapp:${{ steps.version.outputs.version }}
